import kru2uni from "@anthro-ai/krutidev-unicode";

/* ============================================================
   FONT CONVERTER UTILS
   ============================================================
   Supported:

   Unicode → KrutiDev
   Unicode → Shivaji
   Unicode → Preeti

   KrutiDev → Unicode
   Shivaji → Unicode

   Mangal → KrutiDev
   Mangal → Unicode

   IMPORTANT:
   Legacy fonts are ASCII/legacy encoded.
   The output must be displayed using the matching font.
   ============================================================ */


/* ============================================================
   1. COMMON HELPERS
   ============================================================ */

function preProcess(text) {
  if (typeof text !== "string") return "";

  return text
    .replace(/<\/?p[^>]*>/gi, "\n")
    .replace(/<br\s*\/?>/gi, "\n")
    .replace(/<[^>]+>/g, "")
    .replace(/&nbsp;/gi, " ")
    .replace(/\u00A0/g, " ")
    .replace(/\r\n/g, "\n")
    .replace(/\r/g, "\n")
    .normalize("NFC");
}


/*
 * Normalize common Devanagari sequences.
 *
 * This is intentionally conservative.
 * We do NOT randomly rewrite characters because Marathi/Hindi
 * Unicode can contain valid combinations that must remain intact.
 */
function normalizeDevanagari(text) {
  return text
    .normalize("NFC")
    .replace(/क़/g, "क़")
    .replace(/ख़/g, "ख़")
    .replace(/ग़/g, "ग़")
    .replace(/ज़/g, "ज़")
    .replace(/ड़/g, "ड़")
    .replace(/ढ़/g, "ढ़")
    .replace(/फ़/g, "फ़")
    .replace(/य़/g, "य़")
    .replace(/ऱ/g, "ऱ")
    .replace(/ऴ/g, "ऴ");
}


/* ============================================================
   2. UNICODE REPH HANDLING
   ============================================================ */

/*
 * Unicode:
 *
 *     र् + consonant cluster + matra
 *
 * Legacy:
 *
 *     consonant cluster + matra + Z
 *
 * Example:
 *
 *     र्त   → तZ
 *     र्कि  → fकZ
 *     र्क्षि → fक्षZ
 *
 * This handles a complete consonant cluster instead of only
 * looking at the first consonant.
 */
function moveRephToEnd(text, rephChar = "Z") {
  const consonant = "[क-हऴ]";
  const nukta = "़?";

  const cluster =
    `${consonant}${nukta}(?:्${consonant}${nukta})*`;

  const matras = "[ािीुूृॄेैोौंःँॅॉॊ]*";

  const regex = new RegExp(
    `र्(${cluster})(${matras})`,
    "g"
  );

  return text.replace(regex, `$1$2${rephChar}`);
}


/* ============================================================
   3. CHHOTI-I HANDLING
   ============================================================ */

/*
 * Unicode stores:
 *
 *     कि
 *     क्रि
 *     क्षि
 *
 * Legacy fonts normally require:
 *
 *     f + consonant cluster
 *
 * We move ि to the beginning of the complete consonant cluster.
 */
function moveChhotiI(text, marker = "f") {
  const consonant = "[क-हऴ]";
  const cluster =
    `${consonant}़?(?:्${consonant}़?)*`;

  const regex = new RegExp(
    `(${cluster})ि`,
    "g"
  );

  return text.replace(regex, `${marker}$1`);
}


/* ============================================================
   4. GENERIC LONGEST-MATCH CONVERTER
   ============================================================ */

/*
 * IMPORTANT:
 *
 * We do NOT do:
 *
 *   text.replace(A)
 *   text.replace(B)
 *   text.replace(C)
 *
 * because output generated by A can accidentally become input
 * for B or C.
 *
 * Instead we scan the Unicode text once and always choose the
 * longest matching Unicode token.
 */
function createLongestMatchConverter(mapping) {
  const entries = Object.entries(mapping)
    .filter(([from]) => from.length > 0)
    .sort((a, b) => b[0].length - a[0].length);

  return function convertText(input) {
    if (!input) return "";

    let output = "";
    let index = 0;

    while (index < input.length) {
      let matched = false;

      for (const [from, to] of entries) {
        if (input.startsWith(from, index)) {
          output += to;
          index += from.length;
          matched = true;
          break;
        }
      }

      /*
       * If a character is not part of the legacy mapping,
       * preserve it instead of silently deleting it.
       *
       * This is especially useful for:
       * - English
       * - new Unicode characters
       * - legal punctuation
       * - unknown Marathi symbols
       */
      if (!matched) {
        output += input[index];
        index++;
      }
    }

    return output;
  };
}


/* ============================================================
   5. KRUTIDEV 010 MAPPING
   ============================================================ */

const KRUTIDEV_MAP = {
  /* ----------------------------------------------------------
     Complex / special combinations
     ---------------------------------------------------------- */

  "र्थ्य": "F;k±",
  "र्थि": "fFkZ",
  "श्वा": "Üok",
  "श्व": "Üo",

  "द्ध": ")",
  "ट्ट": "ê",
  "ट्ठ": "ë",
  "ड्ढ": "ï",

  "क्र": "Ø",
  "प्र": "iz",
  "द्र": "nz",
  "म्र": "ez",
  "ग्र": "xz",
  "ब्र": "cz",
  "स्र": "lz",

  "त्र": "=",
  "क्ष्": "{",
  "क्ष": "{k",
  "ज्ञ": "K",
  "श्र": "Jh",

  "त्तिः": "Rfr%",
  "त्ति": "Rfr",
  "त्ती": "Rfh",
  "त्त": "Ù",

  "क्त": "Dr",

  "ह्न": "à",
  "हृ": "º",
  "ह्म": "ã",
  "द्य": "|",

  "ट्र": "Vª",
  "ड्र": "Mª",

  "द्व": "}",

  "ल्ल": "Yy",

  /*
   * These special combinations are included because the
   * legacy encoding for ध contains the same "k" component
   * used by its vowel signs.
   */
  "धो": "/ks",
  "धौ": "/kS",
  "धा": "/kk",
  "धि": "f/k",
  "धी": "/kh",
  "धु": "/kq",
  "धू": "/kw",
  "धे": "/ks",
  "धै": "/kS",
  "धं": "/ka",
  "धः": "/k%",
  "ध्": "/",

  "थो": "Fkks",
  "थौ": "FkkS",
  "था": "Fkk",
  "थि": "fFk",
  "थी": "Fkh",
  "थु": "Fkq",
  "थू": "Fkw",
  "थे": "Fks",
  "थै": "FkS",
  "थं": "Fka",
  "थः": "Fk%",
  "थ्": "F",

  "रू": ":",


  /* ----------------------------------------------------------
     Curly quotes
     ---------------------------------------------------------- */

  "\u2018": "^",
  "\u2019": "*",
  "\u201C": "Þ",
  "\u201D": "ß",


  /* ----------------------------------------------------------
     Punctuation
     ---------------------------------------------------------- */

 "(": "¼",
")": "½",
"=": "¾",

// KrutiDev 010 punctuation
"।": "A",
"?": "\\",
"-": "&",
"µ": "0",
"॰": "]",
",": "]",
".": "-",


  /* ----------------------------------------------------------
     Digits
     ---------------------------------------------------------- */

  "०": "0",
  "१": "1",
  "२": "2",
  "३": "3",
  "४": "4",
  "५": "5",
  "६": "6",
  "७": "7",
  "८": "8",
  "९": "9",


  /* ----------------------------------------------------------
     Half consonants
     ---------------------------------------------------------- */

  "क्": "D",
  "ख्": "[",
  "ग्": "X",
  "घ्": "¿",
  "ङ्": "?",

  "च्": "P",
  "छ्": "N",
  "ज्": "T",
  "झ्": ">",
  "ञ्": "¥",

  "ट्": "V",
  "ठ्": "B",
  "ड्": "M",
  "ढ्": "<",
  "ण्": ".k",

  "त्": "R",
  "द्": "n",
  "ध्": "/",
  "न्": "U",

  "प्": "i",
  "फ्": "Q",
  "ब्": "C",
  "भ्": "H",
  "म्": "e",

  "य्": "¸",
  "र्": "j",
  "ल्": "y",
  "व्": "O",
  "श्": "'",
  "ष्": "\"",
  "स्": "L",
  "ह्": "g",


  /* ----------------------------------------------------------
     Matras
     ---------------------------------------------------------- */

  "ा": "k",
  "ि": "f",
  "ी": "h",
  "ु": "q",
  "ू": "w",
  "ृ": "`",
  "ॄ": "`",
  "े": "s",
  "ै": "S",
  "ो": "ks",
  "ौ": "kS",

  "ं": "a",
  "ँ": "¡",
  "ः": "%",
  "ॅ": "W",
  "ऽ": "·",
  "़": "¸",


  /* ----------------------------------------------------------
     Independent vowels
     ---------------------------------------------------------- */

  "अ": "v",
  "आ": "vk",
  "इ": "b",
  "ई": "bZ",
  "उ": "m",
  "ऊ": "Å",
  "ऋ": "_",
  "ए": ",",
  "ऐ": "S",
  "ओ": "vks",
  "औ": "vkS",
  "अं": "va",
  "अः": "v%",


  /* ----------------------------------------------------------
     Consonants
     ---------------------------------------------------------- */

  "क": "d",
  "ख": "[k",
  "ग": "x",
  "घ": "?k",
  "ङ": "?",

  "च": "p",
  "छ": "N",
  "ज": "t",
  "झ": ">",
  "ञ": "¥",

  "ट": "V",
  "ठ": "B",
  "ड": "M",
  "ढ": "<",
  "ण": ".k",

  "त": "r",
  "थ": "Fk",
  "द": "n",
  "ध": "/k",
  "न": "u",

  "प": "i",
  "फ": "Q",
  "ब": "c",
  "भ": "Hk",
  "म": "e",

  "य": ";",
  "र": "j",
  "ल": "y",
  "व": "o",
  "श": "'k",
  "ष": "\"k",
  "स": "l",
  "ह": "g",
  "ळ": "G",

  "्": "~"
};


/* ============================================================
   6. UNICODE → KRUTIDEV
   ============================================================ */

const convertKrutidev = createLongestMatchConverter(KRUTIDEV_MAP);

export function unicodeToKrutidev(sourceText) {
  if (!sourceText) return "";

  let text = preProcess(sourceText);

  /*
   * Normalize Unicode before processing.
   */
  text = normalizeDevanagari(text);

  /*
   * Handle reph BEFORE chhoti-i.
   */
  text = moveRephToEnd(text, "Z");

  /*
   * Move chhoti-i before the complete consonant cluster.
   */
  text = moveChhotiI(text);

  /*
   * Convert once using longest-match matching.
   */
  return convertKrutidev(text);
}


/* Alias */
export const mangalToKrutidev = unicodeToKrutidev;


/* ============================================================
   7. SHIVAJI 01 MAPPING
   ============================================================ */

const SHIVAJI_MAP = {

  // ----------------------------------------------------------
  // Special / symbols
  // ----------------------------------------------------------

  "ऽ": "|",

  // ----------------------------------------------------------
  // Half consonants
  // ----------------------------------------------------------

  "ख्": "#",
  "क्": "@",
  "घ्": "G",
  "ग्": "g",
  "ङ": "=",

  "च्": "c",
  "झ्": "J",
  "ज्": "j",
  "ञ्": "H",

  "ण्": "N",

  "थ्": "q",
  "त्": "%",
  "ध्": "Q",
  "न्": "n",

  "प्": "P",
  "भ्": "B",
  "म्": "m",

  "य्": "y",
  "ल्": "l",
  "व्": "v",
  "श्": "S",
  "ष्": "Y",
  "स्": "s",

  // ----------------------------------------------------------
  // Consonants
  // ----------------------------------------------------------

  "ख": "K",
  "क": "k",
  "ग": "ga",
  "घ": "Ga",
  "ङ": "=",

  "च": "ca",
  "छ": "C",
  "ज": "ja",
  "झ": "Ja",
  "ञ": "H",

  "ट": "T",
  "ठ": "z",
  "ड": "D",
  "ढ": "Z",
  "ण": "Na",

  "त": "t",
  "थ": "qa",
  "द": "d",
  "ध": "Qa",
  "न": "na",

  "प": "p",
  "फ": "f",
  "ब": "ba",
  "भ": "Ba",
  "म": "ma",

  "य": "ya",
  "र": "r",
  "ल": "la",
  "व": "va",

  "श": "Sa",
  "ष": "Ya",
  "स": "sa",
  "ह": "h",

  // ----------------------------------------------------------
  // Conjuncts
  // ----------------------------------------------------------

  "प्र्": "p`",
  "्र": "`",

  "क्ष": "xa",
  "क्ष्": "x",

  "त्र": "~",
  "ज्ञ": "&",
  "द्य": "V",
  "न्न": "Ù",
  "श्र्": "E",
  "ह्म": "(",
  "द्ध": "w",
  "क्र": "Ë",
  "द्व": "W",
  "त्त्": "<",
  "क्त": ">",
  "द्द": "_",

  // ----------------------------------------------------------
  // Special R combinations
  // ----------------------------------------------------------

  "रु": "É",
  "रू": "$",

  // ----------------------------------------------------------
  // Independent vowels
  // ----------------------------------------------------------

  "औ": "AaO",
  "ओ": "Aao",
  "आ": "Aa",
  "अ": "A",
  "ऐ": "eo",
  "ए": "e",
  "ई": "š",
  "इ": "[",
  "उ": "]",
  "ऋ": "?",

  // ----------------------------------------------------------
  // Matras
  // ----------------------------------------------------------

  "ौ": "aO",
  "ै": "O",
  "ी": "I",
  "ू": "U",
  "ु": "u",
  "ृ": "R",
  "ो": "ao",
  "े": "o",
  "ा": "a",

  // ----------------------------------------------------------
  // Other signs
  // ----------------------------------------------------------

  "ँ": "^M",
  "ं": "M",

  // ----------------------------------------------------------
  // Punctuation
  // ----------------------------------------------------------

  ",": "¸",
  "।": ".",
  "|": ".",

  "(": "³",
  ")": "´",

  // ----------------------------------------------------------
  // Halant
  // ----------------------------------------------------------

  "्": "\\"
};

/*
 * Shivaji has several special sequences where the generic
 * consonant + matra combination is not sufficient.
 */



const SHIVAJI_FINAL_MAP = {
  ...SHIVAJI_MAP
};
const convertShivaji = createLongestMatchConverter(SHIVAJI_FINAL_MAP);


/* ============================================================
   8. UNICODE → SHIVAJI
   ============================================================ */

export function unicodeToShivaji(sourceText) {
  if (!sourceText) return "";

  let text = preProcess(sourceText);

  text = normalizeDevanagari(text);


  // Shivaji reph positioning
  text = moveRephToEnd(text, "-");

  // Shivaji uses "i" for short-i matra positioning
  text = moveChhotiI(text, "i");

  return convertShivaji(text);
}



/* ============================================================
   9. KRUTIDEV → UNICODE
   ============================================================ */

export function krutidevToUnicode(text) {
  if (!text) return "";

  try {
    return kru2uni(text);
  } catch (error) {
    console.error("[FontConverter] KrutiDev → Unicode failed:", error);
    throw new Error("KrutiDev → Unicode conversion failed.");
  }
}


/* ============================================================
   10. SHIVAJI → UNICODE
   ============================================================ */

/*
 * Shivaji and KrutiDev share a large part of their legacy
 * character space, but some Shivaji codes are different.
 *
 * Convert only the known Shivaji-specific codes first.
 */
export function shivajiToUnicode(text) {
  if (!text) return "";

  let t = String(text);

  /*
   * IMPORTANT:
   * Long sequences must be handled before single characters.
   */
  t = t.replace(/n~o/g, "}");

  /*
   * Shivaji-specific conjuncts.
   */
  t = t.replace(/ð/g, ")");
  t = t.replace(/†/g, "ॐ");
  t = t.replace(/J/g, "ऱ");

  /*
   * Shivaji half-letter differences.
   *
   * These are intentionally kept compatible with the existing
   * TNT behaviour.
   */
  t = t.replace(/I/g, "i");
  t = t.replace(/C/g, "c");
  t = t.replace(/E/g, "e");
  t = t.replace(/Y/g, "y");
  t = t.replace(/O/g, "o");

  try {
    return kru2uni(t);
  } catch (error) {
    console.error("[FontConverter] Shivaji → Unicode failed:", error);
    throw new Error("Shivaji → Unicode conversion failed.");
  }
}


/* ============================================================
   11. UNICODE → PREETI
   ============================================================ */

const PREETI_MAP = {
  "द्ध": "If",
  "द्व": "n]o",
  "ट्ट": "q",
  "ट्ठ": "1",
  "ड्ढ": "Zo",
  "क्ष": "If",
  "त्र": "q",
  "ज्ञ": "1",
  "श्र": "Zo",

  "क्": "s",
  "ख्": "v",
  "ग्": "u",
  "घ्": "3",
  "च्": "r",
  "छ्": "5",
  "ज्": "h",
  "झ्": "em",
  "ट्": "6",
  "ठ्": "7",
  "ड्": "8",
  "ढ्": "9",

  "ण्": "0",
  "त्": "t",
  "थ्": "F",
  "द्": "b",
  "ध्": "w",
  "न्": "g",
  "प्": "k",
  "फ्": "km",
  "ब्": "a",
  "भ्": "e",
  "म्": "d",

  "य्": "o",
  "र्": "/",
  "ल्": "n",
  "व्": "j",
  "श्": "z",
  "ष्": "if",
  "स्": ";",
  "ह्": "x",

  "ळ": "Ø",
  "ऱ": "J",
  "ॐ": "†",

  "ा": "-",
  "ि": "f",
  "ी": "L",
  "ु": "'",
  "ू": "\"",
  "ृ": "`",
  "े": "s",
  "ै": "P",
  "ो": "]",
  "ौ": "O",

  "ं": "F",
  "ँ": "M",
  "ः": ";",
  "ॅ": "~",
  "ऽ": "¤",
  "़": "°",

  "अ": "v",
  "आ": "g",
  "इ": "O",
  "ई": "{",
  "उ": "=",
  "ऊ": "+",
  "ऋ": "_",
  "ए": "cf]",
  "ऐ": "{]",
  "ओ": "c",
  "औ": "v",
  "अं": "u",
  "अः": "3",

  "क": "r",
  "ख": "5",
  "ग": "h",
  "घ": "em",
  "ङ": "~",
  "च": "6",
  "छ": "7",
  "ज": "8",
  "झ": "9",
  "ञ": "0",

  "ट": "t",
  "ठ": "F",
  "ड": "b",
  "ढ": "w",
  "ण": "g",

  "त": "k",
  "थ": "km",
  "द": "a",
  "ध": "e",
  "न": "d",

  "प": "o",
  "फ": "/",
  "ब": "n",
  "भ": "j",
  "म": "z",
  "य": "if",
  "र": ";",
  "ल": "x",
  "व": "Ø",

  "श": "J",
  "ष": "†",
  "स": "r",
  "ह": "5",

  "०": "å",
  "१": "!",
  "२": "@",
  "३": "#",
  "४": "$",
  "५": "%",
  "६": "^",
  "७": "&",
  "८": "*",
  "९": "(",
  "।": "A",

  "्": "\\",
  "«": "Z"
};

const convertPreeti = createLongestMatchConverter(PREETI_MAP);


/* ============================================================
   12. UNICODE → PREETI
   ============================================================ */

export function unicodeToPreeti(sourceText) {
  if (!sourceText) return "";

  let text = preProcess(sourceText);

  text = normalizeDevanagari(text);

  /*
   * Preeti reph marker.
   */
  text = moveRephToEnd(text, "«");

  text = moveChhotiI(text);

  return convertPreeti(text);
}


/* ============================================================
   13. MANGAL → UNICODE
   ============================================================ */

/*
 * Mangal is a Unicode Devanagari font.
 *
 * Therefore no legacy encoding conversion is necessary.
 * We only clean HTML and normalize Unicode.
 */
export function mangalToUnicode(text) {
  if (!text) return "";

  return normalizeDevanagari(preProcess(text));
}


/* ============================================================
   14. SUPPORTED CONVERSIONS
   ============================================================ */

export const SUPPORTED_CONVERSIONS = {
  "unicode-to-krutidev": {
    fn: unicodeToKrutidev,
    label: "Unicode → KrutiDev"
  },

  "unicode-to-shivaji": {
    fn: unicodeToShivaji,
    label: "Unicode → Shivaji"
  },

  "unicode-to-preeti": {
    fn: unicodeToPreeti,
    label: "Unicode → Preeti"
  },

  "krutidev-to-unicode": {
    fn: krutidevToUnicode,
    label: "KrutiDev → Unicode"
  },

  "shivaji-to-unicode": {
    fn: shivajiToUnicode,
    label: "Shivaji → Unicode"
  },

  "mangal-to-krutidev": {
    fn: mangalToKrutidev,
    label: "Mangal → KrutiDev"
  },

  "mangal-to-unicode": {
    fn: mangalToUnicode,
    label: "Mangal → Unicode"
  }
};


/* ============================================================
   15. MAIN DISPATCHER
   ============================================================ */

export function convert(conversionType, text) {
  const entry = SUPPORTED_CONVERSIONS[conversionType];

  if (!entry) {
    throw new Error(
      `Unsupported conversion: "${conversionType}". ` +
      `Options: ${Object.keys(SUPPORTED_CONVERSIONS).join(", ")}`
    );
  }

  if (typeof text !== "string") {
    throw new Error("Conversion input must be a string.");
  }

  return entry.fn(text);
}


/* ============================================================
   16. SMALL TEST HELPER
   ============================================================ */

export function testFontConversion() {
  const samples = [
    "महोदय",
    "उपरोक्त विषयी",
    "संदर्भांकित",
    "चौकशी",
    "अर्जदार",
    "फसवणूक",
    "कायदेशीर कारवाई",
    "निष्कर्ष व शिफारस",
    "क्ष ज्ञ त्र श्र",
    "द्व द्ध त्त क्त",
    "क्र प्र ग्र ब्र",
    "शर्त",
    "रक्कम",
    "मिळाली"
  ];

  return {
    krutidev: samples.map((text) => ({
      unicode: text,
      converted: unicodeToKrutidev(text)
    })),

    shivaji: samples.map((text) => ({
      unicode: text,
      converted: unicodeToShivaji(text)
    }))
  };
}